"""changed Chat

Revision ID: e4dedd736c43
Revises: fe52d23c2c0a
Create Date: 2026-04-20 16:45:21.114593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4dedd736c43'
down_revision: Union[str, Sequence[str], None] = 'fe52d23c2c0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'orders_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats', 'orders_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
